Update did-auth spec with new definitions
rsksmart/rif-identity-docs pull request #10
Opened 2020-10-07 20:26 UTC by javiesses

- Update description
- Update sequence diagram

2020-10-08 20:57 UTC, ilanolkies requested changes

2020-10-08 20:57 UTC, ilanolkies commented on ssi/specs/did-auth.markdown
> +2. Bob creates a random challenge to send to Alice, stores the pair `did-challenge`, and responses with `{ challenge, schemas }` were `schemas` is an array of published and well known names of _W3C V
```suggestion
2. Bob creates a random challenge to send to Alice, stores the pair `did-challenge`, and responses with `{ challenge, schemas }` were `schemas` is an array of published names of _W3C Verifiable Credentials JSON Schema_. IE: `{ challenge: 'qwerty12345678', schemas: ['EmailCredentialSchema'] }`
```

Needs to define what "published is"

2020-10-08 20:57 UTC, ilanolkies commented on ssi/specs/did-auth.markdown
> +2. Bob creates a random challenge to send to Alice, stores the pair `did-challenge`, and responses with `{ challenge, schemas }` were `schemas` is an array of published and well known names of _W3C V
`schemas` i would change it for `sdr`, selective disclosure request. I would also make it more robust, specifying the sdr is asking for credentials
```
{
  challenge,
  sdr: {
    credentials: ['EmailCredential']
  }
}
```

2020-10-09 02:19 UTC, javiesses commented on ssi/specs/did-auth.markdown
> +2. Bob creates a random challenge to send to Alice, stores the pair `did-challenge`, and responses with `{ challenge, schemas }` were `schemas` is an array of published and well known names of _W3C V
I think this is a good option if we might add other stuff to the `sdr`, not just credentials. IE: `declarativeDetails`

2020-10-09 20:53 UTC, ilanolkies commented on ssi/specs/did-auth.markdown
> +2. Bob creates a random challenge to send to Alice, stores the pair `did-challenge`, and responses with `{ challenge, schemas }` were `schemas` is an array of published and well known names of _W3C V
Let's check uPort DAF compatibility 😄

2020-10-09 20:54 UTC, ilanolkies commented on ssi/specs/did-auth.markdown
>  5. Alice accesses next HTTPS requests using header `Authentication` with the Credential received
What about cookies?

2020-10-13 16:10 UTC, merged