Cookies & Refresh token
rsksmart/rif-identity-docs pull request #14
Opened 2020-10-16 15:26 UTC by javiesses

- Added `How to send tokens` section
- Added refresh token approach (taken from OAuth 2.0)
- Updated DID Auth diagrams

2020-10-20 10:32 UTC, jessgusclark approved these changes
:+1:

2020-10-20 17:22 UTC, ilanolkies requested changes

2020-10-20 17:22 UTC, ilanolkies commented on ssi/specs/did-auth.markdown
> +This protocol is based on CHAP{% include ref.html id="11" %} authentication protocol, OAuth 2.0 Authorization Framework{% include ref.html id="13" %} and Decentralized Identifiers (DIDs) v1.0 {% incl
We are still basing this on SDRs

2020-10-20 17:22 UTC, ilanolkies commented on ssi/specs/did-auth.markdown
> +- Allow the user to refresh the _access token_ once it expired - sessions will still be valid beyond the _access token_ expiration time
This is part of the implementation, not design nor motivation. I would say the motivation is to make sessions short to avoid certain attacks

2020-10-20 17:22 UTC, ilanolkies commented on ssi/specs/did-auth.markdown
> +- Give the user control of the session by providing a logout endpoint that will mark the current session as closed
Is this really important? Does this drive our efforts?

2020-10-20 17:22 UTC, ilanolkies commented on ssi/specs/did-auth.markdown
I would add two sections first, _Motivation_ and _State of the art_. This is kind of introduction to our protocol design and why is important to get the protocol standarized.

2020-10-20 17:22 UTC, ilanolkies commented on ssi/specs/did-auth.markdown
>  1. Alice sends `POST /request_auth { did }` to Bob, where `did` is Alice's DID
2 comments on all this section.
1. Let's use _user_ and _app_, is confusing to read _Alice_ and _Bob_ in this case. This nomenclature is better when describing people that are indifferent, _generic_ entities in the protocol. https://en.wikipedia.org/wiki/Alice_and_Bob
2. I would add references to each of the steps in the sequence diagram. Each step should be mapped into an arrow of the sequence diagram.

2020-10-20 17:22 UTC, ilanolkies commented on ssi/specs/did-auth.markdown
> +## How to calculate a deterministic challenge
This can go in an _Appendix_ section. It is not part of the core principles.

2020-10-20 17:22 UTC, ilanolkies commented on ssi/specs/did-auth.markdown
> +```javascript
This is very JS. Using pseudocode for this is always better :)

2020-10-20 17:22 UTC, ilanolkies commented on ssi/specs/did-auth.markdown
> +By doing this, the `challenge` will be valid during maximum 5 minutes. Once the user sends the signed challenge back to the service, the server MUST perform the same calculation and the received chal
I would like to read the word `modulo` here. That describes perfectly what this is doing

2020-10-20 17:22 UTC, ilanolkies commented on ssi/specs/did-auth.markdown
> +It must be placed in the body of the request as a `refresh-token` field.
Why are we using `refresh-token` and not `refresh_token` as we did for `request_auth`? I would follow a unique pattern for all endpoints

2020-10-20 17:22 UTC, ilanolkies commented on ssi/specs/did-auth.markdown
> +- Separate authentication server from resource server
What is this?

2020-10-20 17:22 UTC, ilanolkies commented on ssi/specs/did-auth.markdown
> +- Allow the user to associate many dids to the same identity, so the business logic over `did1` and `did2` should be the same if both dids are associated.
```suggestion
- Allow the user to express control of different identities in a private manner. Lets the user use different identities for a single registration
```

2020-10-20 17:22 UTC, ilanolkies commented on ssi/specs/did-auth.markdown
> +3. Alice receives Bob's `challenge` and creates a JWT {% include ref.html id="1" %} with the following payload:
Let's add the _registration_ flow as the one and only time you need to disclose your information. SDRs should still be part of this protocol

2020-10-20 17:39 UTC, javiesses commented on ssi/specs/did-auth.markdown
> +- Separate authentication server from resource server
This may be also part of the implementation. The goal is to differentiate the server that keeps the session data from the one that has the resources (API), so this last server could be stateless.

By doing so, the user authenticates and refresh tokens with a Security Token Service that emits tokens can be used in another services that owns the business resources (ie: `/products`)

2020-10-20 17:56 UTC, ilanolkies commented on ssi/specs/did-auth.markdown
> +- Separate authentication server from resource server
```suggestion
- Separate authentication server from resource server. The goal is to differentiate the server that keeps the session data from the one that has the resources (API), so this last server could be stateless. By doing so, the user authenticates and refresh tokens with a Security Token Service that emits tokens can be used in another services that owns the business resources (ie: `/products`)
```

2020-10-23 14:55 UTC, ilanolkies requested changes
Inconsistent use of _his_, _her_, _their_ for "user". I would always use a non sex designating word.

2020-10-23 15:27 UTC, ilanolkies requested changes
Half way reviewed

2020-10-23 15:27 UTC, ilanolkies commented on ssi/specs/did-auth.markdown
> +Nowadays, authentication is handled in a centralized way. Most applications delegate the process of authenticating users to third-party services ([OIDC](https://openid.net/connect/)), and the authent
I didn't understand this part 
"Today's decentralized applications cannot rely on this authentication, since they must prove that the user is the one who controls their information and not a third party"

2020-10-23 15:27 UTC, ilanolkies commented on ssi/specs/did-auth.markdown
> +The motivation of this protocol is to provide a user centric authentication and registration mechanism to be used by backend services of the web 3.0. There are two main type of services: _open_ (publ
```suggestion
The motivation of this protocol is to provide user centric registration and authentication mechanisms to be used by services of the web 3.0. We identify two main type of services: _open_ (public access) and _permissioned_ (the user must provide certain information to access it). This protocol allows an external service to prove that the user is in control of their did and, optionally, enables the application to ask the user to share specific private information associated to their DID, in order to register the them.
```

2020-10-23 15:27 UTC, ilanolkies commented on ssi/specs/did-auth.markdown
> +It uses HTTPS as the message transport layer.
```suggestion
Initially, it is design to use HTTPS as the message transport layer, but can be ported to a different one.
```

2020-10-23 15:27 UTC, ilanolkies commented on ssi/specs/did-auth.markdown
> +# DID authentication - a challenge–response authentication model based on DIDs
```suggestion
## DID authentication - a challenge–response authentication model based on DIDs
```

2020-10-23 15:27 UTC, ilanolkies commented on ssi/specs/did-auth.markdown
> +# Table of contents
```suggestion
### Table of contents
```

2020-10-23 15:27 UTC, ilanolkies commented on ssi/specs/did-auth.markdown
> +# State of the art
```suggestion
### State of the art
```

2020-10-23 15:27 UTC, ilanolkies commented on ssi/specs/did-auth.markdown
> +# Endpoints
```suggestion
```

2020-10-23 15:27 UTC, ilanolkies commented on ssi/specs/did-auth.markdown
> +## Signup
```suggestion
### Signup
```

2020-10-23 15:27 UTC, ilanolkies commented on ssi/specs/did-auth.markdown
> +This section is OPTIONAL, it depends on the service needings. Some services may not need to register users before letting them enter in.
```suggestion
Services usually need to register users before letting them in. This means the service requires some specific information to be share by the user (e.g.: user's email).

> This part of the protocol is OPTIONAL, it depends on the service needs. Some services may not need to register users before letting them enter in.
```

2020-10-23 15:27 UTC, ilanolkies commented on ssi/specs/did-auth.markdown
> +1. _Client_ sends `POST /request-signup { did }` to _Service_, where `did` is _User_'s DID
```suggestion
1. _Client_ sends `POST /request-signup { did }` to _Service_, where `did` is _User_'s DID
```

How will the apps know if they need to fetch this or `request-auth` directly? Or is it that they always fetch this and then they fallback into `/request-auth`?

Let's think of a public service that you know it is DID AUth compliant but you are not sure yet of what the registration flow is.

2020-10-23 15:27 UTC, ilanolkies commented on ssi/specs/did-auth.markdown
```suggestion

*The challenge can be non-deterministic, but the service will need to store challenge state. See [How to calculate a deterministic challenge](#how-to-calculate-a-deterministic-challenge)

```

2020-10-23 15:27 UTC, ilanolkies commented on ssi/specs/did-auth.markdown
> +2. _Service_ creates a deterministic _challenge_ (see [How to calculate a deterministic challenge](#how-to-calculate-a-deterministic-challenge)) to send to _Client_ and responds with `{ challenge, sd
```suggestion
2. _Service_ creates a random deterministic* _challenge_ to send to _Client_ and responds with `{ challenge, sdr }` were `sdr` is the [selective disclosure request](#request) defined by the _Service_.
```

See comment bellow

2020-10-23 15:27 UTC, ilanolkies commented on ssi/specs/did-auth.markdown
> +and prompts the _User_ to sign it with her `did`'s private key.
Wrong indentation. Breaking `ol`

2020-10-23 15:27 UTC, ilanolkies commented on ssi/specs/did-auth.markdown
> +```
Same

2020-10-23 15:27 UTC, ilanolkies commented on ssi/specs/did-auth.markdown
> +6. _Service_ verifies JWT signature, checks if the received `challenge` is ok (by calculating the deterministic one again), and performs business logic over the `sdr`. If it is a valid user, it logge
```suggestion
6. _Service_ verifies JWT signature, checks if the received `challenge` is matches the challenge requested, and performs business logic over the `sdr`. If it is a valid user, it logges her in by creating an _access token_ and a _refresh token_.
```

2020-10-25 17:08 UTC, javiesses commented on ssi/specs/did-auth.markdown
> +and prompts the _User_ to sign it with her `did`'s private key.
It is not breaking it

<img width="803" alt="Screen Shot 2020-10-25 at 14 07 10" src="https://user-images.githubusercontent.com/1650329/97113807-6eeb0400-16cb-11eb-889e-733a6a1bffe8.png">

2020-10-27 23:57 UTC, ilanolkies approved these changes

2020-10-27 23:58 UTC, merged