Clean up and organize
rsksmart/rif-identity-docs pull request #15
Opened 2020-10-19 15:58 UTC by javiesses

- Update index with more links
- Sum up missing stuff
- Created new blank documentation pages to correctly build links

2020-10-19 17:13 UTC, jessgusclark approved these changes
👍

2020-10-20 17:58 UTC, ilanolkies approved these changes

2020-10-20 18:11 UTC, miltonwg commented on ssi/applications/index.markdown
> +- [Issuer app](./issuer-app) - application that serves as the credential request manager. It allows to grant-deny requests or revoke existing credentials
```suggestion
- [Issuer app](./issuer-app) - web application that serves as the credential request manager. It allows to grant-deny requests, issue verifiable credentials and revoke existing ones.
```

2020-10-20 18:12 UTC, miltonwg commented on ssi/applications/index.markdown
> +- [Holder app](./holder-app) - wallet used to store declarative details and credentials of it’s users
```suggestion
- [Holder app](./holder-app) - mobile wallet used to store verifiable credentials and declarative details of it’s users
```

2020-10-20 18:14 UTC, miltonwg commented on ssi/applications/index.markdown
> +- [Verifier app](./verifier-app) - QR scanner app that verifies Verifiable Presentations
```suggestion
- [Verifier app](./verifier-app) - QR scanner mobile app that verifies verifiable presentations (of verifiable credentials)
```

2020-10-20 18:17 UTC, miltonwg commented on ssi/services/index.markdown
>  RIF Self-Sovereign Identity solution provides four main services to interact with:
```suggestion
RIF Self-Sovereign Identity solution provides two main services to interact with:
```

I see only 2 services listed

2020-10-20 18:20 UTC, miltonwg commented on ssi/services/index.markdown
> +- [Issuer service](./issuer-service) - serves for an application that allows receiving credential issuance requests and approving them manually
```suggestion
- [Issuer service](./issuer-service) - web application that receives verifiable credential issuance requests and lets the user to manually deny or approve them (thus, issuing the verifiable credential)
```

2020-10-20 18:21 UTC, miltonwg requested changes
Some changes requested.

2020-10-20 18:23 UTC, ilanolkies commented on ssi/services/index.markdown
> +- [Issuer service](./issuer-service) - serves for an application that allows receiving credential issuance requests and approving them manually
This is not the web app, is serving for the web app.
```suggestion
- [Issuer service](./issuer-service) - serves for a [web application](../apps/issuer-app) that receives verifiable credential issuance requests and lets the user to manually deny or approve them (thus, issuing the verifiable credential)
```

2020-10-20 18:36 UTC, miltonwg approved these changes

2020-10-20 18:52 UTC, merged