change word in spec
rsksmart/rif-identity-docs pull request #9
Opened 2020-10-07 13:17 UTC by miltonwg

2020-10-07 20:55 UTC, ilanolkies requested changes
LGTM

2020-10-07 20:55 UTC, ilanolkies commented on README.md
>  </p>
I would move this bellow the title, without changing the header format.

2020-10-07 20:55 UTC, ilanolkies commented on README.md
> +<p align="left">
```suggestion
<p align="middle">
```

:)

2020-10-07 20:55 UTC, ilanolkies commented on ssi/specs/convey-service.markdown
> +Convey service: cachés and publishes files into IPFS
```suggestion
Alice: wants to share a file with Bob showing a QR code
Bob: wants to read the file using a QR code scanner
Convey service: cachés and publishes files into IPFS
```

2020-10-07 20:55 UTC, ilanolkies commented on ssi/specs/credential-requests.markdown
> +## Verifiable Credential requests protocol - a simple protocol for request, grant and receive verifiable credential case
_Verifiable credential_ or _Verificable Credential_?

2020-10-07 20:55 UTC, ilanolkies commented on ssi/specs/credential-requests.markdown
> +This protocol is held by two entities: the _issuer_ and the _holder_. The issuer is a public entity that issues a specific type of credential, the holder is a user who wishes to acquire that credenti
Is that necessary? What if he is delegated or was transferred the ownership of an identity. I would say "controls the identity".

2020-10-07 20:55 UTC, ilanolkies commented on ssi/specs/credential-requests.markdown
> +- Schema discoverability methods
```suggestion
- Standard method for schema discovery
```

2020-10-14 13:38 UTC, miltonwg commented on ssi/specs/convey-service.markdown
> +Convey service: cachés and publishes files into IPFS
@ilanolkies I added the 2 spaces for the preview to take the EOL.
If not the preview is like this:

<img width="980" alt="image" src="https://user-images.githubusercontent.com/5920311/95996747-6a8c3480-0e09-11eb-9efb-703adabadd88.png">


https://github.com/rsksmart/rif-identity-docs/blob/master/ssi/specs/convey-service.markdown

2020-10-14 13:50 UTC, miltonwg commented on ssi/specs/credential-requests.markdown
> +This protocol is held by two entities: the _issuer_ and the _holder_. The issuer is a public entity that issues a specific type of credential, the holder is a user who wishes to acquire that credenti
@ilanolkies 
If he has a delegated or transferred identity, in both cases he would also be controlling the private key associated to a DID.
In which cases he wouldn't be controlling a private key associated to a DID?

I want to emphasize this to explain it as simple as possible. The concept "control an identity" in the end is controlling the private keys associated to a DID.

What do you think?

2020-10-14 14:10 UTC, miltonwg commented on README.md
>  </p>
Changes commited!

2020-10-17 21:43 UTC, ilanolkies commented on ssi/specs/credential-requests.markdown
> +This protocol is held by two entities: the _issuer_ and the _holder_. The issuer is a public entity that issues a specific type of credential, the holder is a user who wishes to acquire that credenti
What about

```suggestion
This protocol is held by two entities: the _issuer_ and the _holder_. The issuer is a public entity that issues a specific type of credential, the holder is a user who wishes to acquire that credential and controls a certain DID. The issuer may require the holder to share specific information. This information can be either data input by the user in a declarative way (declarative details) or other credentials issued by the same issuer or another entity.
```

2020-10-20 13:53 UTC, ilanolkies approved these changes
You rock 🤟🏻

2020-10-20 13:53 UTC, merged